kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/connects-to: >-
      [{"apiVersion":"apps/v1","kind":"Deployment","name":"mysql"},{"apiVersion":"apps.openshift.io/v1","kind":"DeploymentConfig","name":"mysql"}]
    app.openshift.io/route-disabled: 'false'
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/shantanu-ghosh/travel-recommendation.git'
    deployment.kubernetes.io/revision: '9'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"travel-recommendation-engine:latest","namespace":"hackathon2023-prometheus"},"fieldPath":"spec.template.spec.containers[?(@.name==\"travel-recommendation-engine\")].image","pause":"false"}]
    openshift.io/generated-by: OpenShiftWebConsole
  resourceVersion: '163468588'
  name: travel-recommendation-engine
  uid: ba07d9f7-d96c-4ae3-91fd-c35e3db0c8b8
  creationTimestamp: '2023-05-08T09:29:54Z'
  generation: 39
  managedFields:
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2023-05-08T09:45:55Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:spec':
              'f:containers':
                'k:{"name":"travel-recommendation-engine"}':
                  'f:image': {}
    - manager: Mozilla
      operation: Update
      apiVersion: apps/v1
      time: '2023-06-04T11:11:17Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:alpha.image.policy.openshift.io/resolve-names': {}
            'f:app.openshift.io/connects-to': {}
            'f:app.openshift.io/route-disabled': {}
            'f:app.openshift.io/vcs-ref': {}
            'f:app.openshift.io/vcs-uri': {}
            'f:image.openshift.io/triggers': {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            'f:app.openshift.io/runtime': {}
            'f:our-travel-recommendation-app': {}
            'f:app': {}
            'f:app.kubernetes.io/name': {}
            .: {}
            'f:app.kubernetes.io/part-of': {}
            'f:app.openshift.io/runtime-version': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/component': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:app': {}
                'f:deployment': {}
            'f:spec':
              'f:containers':
                'k:{"name":"travel-recommendation-engine"}':
                  .: {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8080,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:resources':
                    .: {}
                    'f:limits':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                    'f:requests':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2023-06-04T11:37:56Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"ReplicaFailure"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:unavailableReplicas': {}
      subresource: status
  namespace: hackathon2023-prometheus
  labels:
    app: travel-recommendation-engine
    app.kubernetes.io/component: travel-recommendation-engine
    app.kubernetes.io/instance: travel-recommendation-engine
    app.kubernetes.io/name: travel-recommendation-engine
    app.kubernetes.io/part-of: travel-recommendation
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.9-ubi8
    our-travel-recommendation-app: ''
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travel-recommendation-engine
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: travel-recommendation-engine
        deployment: travel-recommendation-engine
    spec:
      containers:
        - name: travel-recommendation-engine
          image: >-
            image-registry.openshift-image-registry.svc:5000/hackathon2023-prometheus/travel-recommendation-engine@sha256:41144d92bf4bf58088471261dfa5e159e7e0195ef2f637e20f8812a44d1c31e4
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: '2'
              memory: 1Gi
            requests:
              cpu: '1'
              memory: 200Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 39
  replicas: 1
  readyReplicas: 1
  availableReplicas: 1
  unavailableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2023-06-03T17:22:40Z'
      lastTransitionTime: '2023-06-03T17:22:40Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: ReplicaFailure
      status: 'True'
      lastUpdateTime: '2023-06-04T11:37:56Z'
      lastTransitionTime: '2023-06-04T11:37:56Z'
      reason: FailedCreate
      message: >-
        pods "travel-recommendation-engine-68ff5d46cb-cgmlc" is forbidden:
        maximum cpu usage per Container is 1, but limit is 2
    - type: Progressing
      status: 'False'
      lastUpdateTime: '2023-06-04T11:47:57Z'
      lastTransitionTime: '2023-06-04T11:47:57Z'
      reason: ProgressDeadlineExceeded
      message: >-
        ReplicaSet "travel-recommendation-engine-68ff5d46cb" has timed out
        progressing.
