kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    app.openshift.io/connects-to: >-
      [{"apiVersion":"apps.openshift.io/v1","kind":"DeploymentConfig","name":"mysql"},{"apiVersion":"apps/v1","kind":"Deployment","name":"travel-recommendation-engine"}]
    deployment.kubernetes.io/revision: '12'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"travel-ui","namespace":"hackathon2023-prometheus"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"travel-ui"}},"template":{"metadata":{"labels":{"app":"travel-ui"}},"spec":{"containers":[{"image":"image-registry.openshift-image-registry.svc:5000/hackathon2023-prometheus/trav-reco-ui","name":"travel-ui","ports":[{"containerPort":8000}]}]}}}}
  resourceVersion: '213470386'
  name: travel-ui
  uid: 04486e4e-74a0-49fd-aa22-d25f8bfc24a8
  creationTimestamp: '2023-05-23T10:25:59Z'
  generation: 40
  managedFields:
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: apps/v1
      time: '2023-05-30T09:02:56Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:app': {}
            'f:spec':
              'f:containers':
                'k:{"name":"travel-ui"}':
                  .: {}
                  'f:image': {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8000,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:resources': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
    - manager: Mozilla
      operation: Update
      apiVersion: apps/v1
      time: '2023-06-04T10:52:23Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:app.openshift.io/connects-to': {}
          'f:labels':
            .: {}
            'f:app.kubernetes.io/part-of': {}
        'f:spec':
          'f:template':
            'f:spec':
              'f:containers':
                'k:{"name":"travel-ui"}':
                  'f:envFrom': {}
                  'f:livenessProbe':
                    .: {}
                    'f:failureThreshold': {}
                    'f:httpGet':
                      .: {}
                      'f:path': {}
                      'f:port': {}
                      'f:scheme': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:timeoutSeconds': {}
                  'f:readinessProbe':
                    .: {}
                    'f:failureThreshold': {}
                    'f:httpGet':
                      .: {}
                      'f:path': {}
                      'f:port': {}
                      'f:scheme': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:timeoutSeconds': {}
                  'f:resources':
                    'f:limits':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                    'f:requests':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                  'f:startupProbe':
                    .: {}
                    'f:failureThreshold': {}
                    'f:httpGet':
                      .: {}
                      'f:path': {}
                      'f:port': {}
                      'f:scheme': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:timeoutSeconds': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2023-07-04T10:53:16Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"ReplicaFailure"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:unavailableReplicas': {}
      subresource: status
  namespace: hackathon2023-prometheus
  labels:
    app.kubernetes.io/part-of: travel-recommendation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travel-ui
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: travel-ui
    spec:
      containers:
        - resources:
            limits:
              cpu: '2'
              memory: 500Mi
            requests:
              cpu: '1'
              memory: 200Mi
          readinessProbe:
            httpGet:
              path: /
              port: 8000
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: travel-ui
          livenessProbe:
            httpGet:
              path: /
              port: 8000
              scheme: HTTP
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          ports:
            - containerPort: 8000
              protocol: TCP
          imagePullPolicy: Always
          startupProbe:
            httpGet:
              path: /
              port: 8000
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePolicy: File
          envFrom:
            - configMapRef:
                name: cm-travel-ui
            - secretRef:
                name: mysql-secrets
          image: >-
            image-registry.openshift-image-registry.svc:5000/hackathon2023-prometheus/trav-reco-ui
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 40
  replicas: 1
  readyReplicas: 1
  availableReplicas: 1
  unavailableReplicas: 1
  conditions:
    - type: ReplicaFailure
      status: 'True'
      lastUpdateTime: '2023-06-04T10:52:23Z'
      lastTransitionTime: '2023-06-04T10:52:23Z'
      reason: FailedCreate
      message: >-
        pods "travel-ui-55f48cbb9f-nfg4l" is forbidden: maximum cpu usage per
        Container is 1, but limit is 2
    - type: Available
      status: 'True'
      lastUpdateTime: '2023-07-04T10:53:16Z'
      lastTransitionTime: '2023-07-04T10:53:16Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'False'
      lastUpdateTime: '2023-07-04T11:03:17Z'
      lastTransitionTime: '2023-07-04T11:03:17Z'
      reason: ProgressDeadlineExceeded
      message: ReplicaSet "travel-ui-55f48cbb9f" has timed out progressing.
