kind: LimitRange
apiVersion: v1
metadata:
  name: resource-limits
  namespace: hackathon2023-prometheus
  uid: eadbe2e8-616e-45cc-8aa8-46c3f2801dd5
  resourceVersion: '140608552'
  creationTimestamp: '2023-04-13T08:09:24Z'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2023-05-22T08:42:42Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:limits': {}
spec:
  limits:
    - type: Pod
      max:
        cpu: '2'
        memory: 2Gi
      min:
        cpu: 200m
        memory: 200Mi
    - type: Container
      max:
        cpu: '1'
        memory: 1Gi
      min:
        cpu: 200m
        memory: 200Mi
      default:
        cpu: 500m
        memory: 500Mi
      defaultRequest:
        cpu: 200m
        memory: 200Mi
    - type: openshift.io/Image
      max:
        storage: 1Gi
    - type: openshift.io/ImageStream
      max:
        openshift.io/image-tags: '20'
        openshift.io/images: '30'
    - type: PersistentVolumeClaim
      max:
        storage: 10Gi
      min:
        storage: 1Gi
