apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"tekton.dev/v1beta1","kind":"Pipeline","metadata":{"annotations":{},"name":"nodejs-test-pipeline","namespace":"hackathon2023-prometheus"},"spec":{"tasks":[{"name":"fetch-repository","params":[{"name":"url","value":"https://github.com/natarajbasu/redHatHackathon"},{"name":"subdirectory","value":""},{"name":"deleteExisting","value":"true"}],"taskRef":{"kind":"ClusterTask","name":"git-clone"},"workspaces":[{"name":"output","workspace":"shared-workspace"}]},{"name":"build","params":[{"name":"IMAGE","value":"image-registry.openshift-image-registry.svc:5000/nodejs-pipeline/nodejs:1.0"},{"name":"TLSVERIFY","value":"false"}],"runAfter":["fetch-repository"],"taskRef":{"kind":"ClusterTask","name":"s2i-nodejs"},"workspaces":[{"name":"source","workspace":"shared-workspace"}]},{"name":"fetch-config-repository","params":[{"name":"url","value":"https://github.com/natarajbasu/redHatHackathon"},{"name":"subdirectory","value":""},{"name":"deleteExisting","value":"true"}],"runAfter":["build"],"taskRef":{"kind":"ClusterTask","name":"git-clone"},"workspaces":[{"name":"output","workspace":"shared-workspace"}]},{"name":"apply-manifests","runAfter":["fetch-config-repository"],"taskRef":{"kind":"Task","name":"apply-manifests"},"workspaces":[{"name":"output","workspace":"shared-workspace"}]}],"workspaces":[{"name":"shared-workspace"}]}}
  creationTimestamp: '2023-05-16T12:01:29Z'
  generation: 21
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
        'f:spec': {}
      manager: kubectl-client-side-apply
      operation: Update
      time: '2023-05-16T12:01:29Z'
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:finally': {}
          'f:params': {}
          'f:resources': {}
          'f:tasks': {}
          'f:workspaces': {}
      manager: Mozilla
      operation: Update
      time: '2023-05-22T10:35:37Z'
  name: nodejs-test-pipeline
  namespace: hackathon2023-prometheus
  resourceVersion: '171429543'
  uid: 7cc6a099-dba8-4a3e-9268-9949a317fc8f
spec:
  params:
    - default: hackathon2023-prometheus
      name: context.pipelineRun.namespace
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: 'https://github.com/natarajbasu/redHatHackathon'
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: build
      params:
        - name: IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/hackathon2023-prometheus/trav-reco-ui
        - name: TLSVERIFY
          value: 'false'
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: s2i-nodejs
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: apply-manifests
      runAfter:
        - build
      taskRef:
        kind: Task
        name: apply-manifests
      workspaces:
        - name: output
          workspace: shared-workspace
  workspaces:
    - name: shared-workspace
