apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: '2023-05-16T11:51:32Z'
  generation: 1
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:params': {}
          'f:steps': {}
          'f:workspaces': {}
      manager: kubectl-create
      operation: Update
      time: '2023-05-16T11:51:32Z'
  name: apply-manifests
  namespace: hackathon2023-prometheus
  resourceVersion: '130160541'
  uid: af7e0e8e-9f86-4dec-b033-f911134b5f2a
spec:
  params:
    - default: .
      description: The directory in source that contains yaml manifests
      name: manifest_dir
      type: string
  steps:
    - command:
        - /bin/bash
        - '-c'
        - oc apply -f $(inputs.params.manifest_dir)/pipelines/deployment.yml
        - oc apply -f $(inputs.params.manifest_dir)/pipelines/service.yml
      image: 'quay.io/openshift/origin-cli:latest'
      name: apply-manifests
      resources: {}
      workingDir: /workspace/output
  workspaces:
    - name: output
