kind: Service
apiVersion: v1
metadata:
  name: travel-recommendation-engine
  namespace: hackathon2023-prometheus
  uid: a029b039-2322-4dbc-b02d-4304c30fae1a
  resourceVersion: '116033010'
  creationTimestamp: '2023-05-08T09:29:54Z'
  labels:
    app: travel-recommendation-engine
    app.kubernetes.io/component: travel-recommendation-engine
    app.kubernetes.io/instance: travel-recommendation-engine
    app.kubernetes.io/name: travel-recommendation-engine
    app.kubernetes.io/part-of: travel-recommendation
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.9-ubi8
    our-travel-recommendation-app: ''
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"mysql"}]'
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/shantanu-ghosh/travel-recommendation.git'
    openshift.io/generated-by: OpenShiftWebConsole
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2023-05-08T10:42:01Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:app.openshift.io/connects-to': {}
            'f:app.openshift.io/vcs-ref': {}
            'f:app.openshift.io/vcs-uri': {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            'f:app.openshift.io/runtime': {}
            'f:our-travel-recommendation-app': {}
            'f:app': {}
            'f:app.kubernetes.io/name': {}
            .: {}
            'f:app.kubernetes.io/part-of': {}
            'f:app.openshift.io/runtime-version': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/component': {}
        'f:spec':
          'f:internalTrafficPolicy': {}
          'f:ports':
            .: {}
            'k:{"port":10000,"protocol":"TCP"}':
              .: {}
              'f:name': {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
          'f:selector': {}
          'f:sessionAffinity': {}
          'f:type': {}
spec:
  clusterIP: 172.21.33.250
  ipFamilies:
    - IPv4
  ports:
    - name: 10000-tcp
      protocol: TCP
      port: 10000
      targetPort: 10000
  internalTrafficPolicy: Cluster
  clusterIPs:
    - 172.21.33.250
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: travel-recommendation-engine
    deployment: travel-recommendation-engine
status:
  loadBalancer: {}
