kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    ibm.io/provisioning-status: complete
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"build-source-pvc","namespace":"hackathon2023-prometheus"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}}}}
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: ibm.io/ibmc-block
    volume.kubernetes.io/storage-provisioner: ibm.io/ibmc-block
  resourceVersion: '130172158'
  name: build-source-pvc
  uid: 8829f18e-26a4-47a9-8dd9-6f082ba9180a
  creationTimestamp: '2023-05-16T11:58:39Z'
  managedFields:
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: v1
      time: '2023-05-16T11:58:39Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
        'f:spec':
          'f:accessModes': {}
          'f:resources':
            'f:requests':
              .: {}
              'f:storage': {}
          'f:volumeMode': {}
    - manager: provisioner
      operation: Update
      apiVersion: v1
      time: '2023-05-16T11:58:39Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:ibm.io/provisioning-status': {}
          'f:labels':
            .: {}
            'f:region': {}
            'f:zone': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2023-05-16T11:59:22Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:pv.kubernetes.io/bind-completed': {}
            'f:pv.kubernetes.io/bound-by-controller': {}
            'f:volume.beta.kubernetes.io/storage-provisioner': {}
            'f:volume.kubernetes.io/storage-provisioner': {}
        'f:spec':
          'f:volumeName': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2023-05-16T11:59:22Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:accessModes': {}
          'f:capacity':
            .: {}
            'f:storage': {}
          'f:phase': {}
      subresource: status
  namespace: hackathon2023-prometheus
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    region: us-east
    zone: wdc04
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pvc-8829f18e-26a4-47a9-8dd9-6f082ba9180a
  storageClassName: ibmc-block-gold
  volumeMode: Filesystem
status:
  phase: Bound
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
