kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  resourceVersion: '153369092'
  name: mysql
  uid: 6cccaf5e-809b-454c-9142-9741571e3270
  creationTimestamp: '2023-05-05T13:34:28Z'
  generation: 2
  managedFields:
    - manager: Go-http-client
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2023-05-05T13:34:28Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:imageChangeTriggers': {}
          'f:lastVersion': {}
    - manager: oc
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2023-05-05T13:34:28Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
        'f:spec':
          'f:output':
            'f:to': {}
          'f:runPolicy': {}
          'f:source':
            'f:contextDir': {}
            'f:git':
              .: {}
              'f:uri': {}
            'f:type': {}
          'f:strategy':
            'f:sourceStrategy':
              .: {}
              'f:from': {}
            'f:type': {}
          'f:triggers': {}
  namespace: hackathon2023-prometheus
  labels:
    app: mysql
    app.kubernetes.io/component: mysql
    app.kubernetes.io/instance: mysql
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'mysql:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'mysql:8.0'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/sclorg/mysql-container.git'
    contextDir: examples/extend-image
  triggers:
    - type: GitHub
      github:
        secret: OTT2sfEHjiSEgwIl1dd3
    - type: Generic
      generic:
        secret: uzqTV-Q_bLbeLmQdBUvp
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
  runPolicy: Serial
status:
  lastVersion: 1
  imageChangeTriggers:
    - lastTriggeredImageID: >-
        image-registry.openshift-image-registry.svc:5000/openshift/mysql@sha256:daa6533d9385e8342470903788dbacdb239aae362275cc64029a06c6bc6c30b6
      from:
        namespace: openshift
        name: 'mysql:8.0'
      lastTriggerTime: '2023-05-05T13:34:28Z'
